// Code generated by hertz generator.

package user

import (
	sahertz "github.com/click33/sa-token-go/integrations/hertz"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{sahertz.CheckPermission("admin:*")}
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _managerMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{sahertz.CheckRole("manager")}
}

func _publicMw() []app.HandlerFunc {
	return []app.HandlerFunc{sahertz.Ignore()}
}

func _sensitiveMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{sahertz.CheckDisable()}
}

func _userinfoMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{sahertz.CheckLogin()}
}

func _disableMw() []app.HandlerFunc {
	// your code...
	return nil
}
