// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: helloworld/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginId       string                 `protobuf:"bytes,1,opt,name=loginId,proto3" json:"loginId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_helloworld_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetLoginId() string {
	if x != nil {
		return x.LoginId
	}
	return ""
}

// 登录响应
type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_helloworld_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取用户信息请求
type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_helloworld_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{2}
}

// 获取用户信息响应
type GetUserInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReply) Reset() {
	*x = GetUserInfoReply{}
	mi := &file_helloworld_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReply) ProtoMessage() {}

func (x *GetUserInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReply.ProtoReflect.Descriptor instead.
func (*GetUserInfoReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{3}
}

var File_helloworld_v1_user_proto protoreflect.FileDescriptor

const file_helloworld_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x18helloworld/v1/user.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"(\n" +
	"\fLoginRequest\x12\x18\n" +
	"\aloginId\x18\x01 \x01(\tR\aloginId\"\"\n" +
	"\n" +
	"LoginReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x14\n" +
	"\x12GetUserInfoRequest\"\x12\n" +
	"\x10GetUserInfoReply2\xc9\x01\n" +
	"\x04User\x12V\n" +
	"\x05Login\x12\x1b.helloworld.v1.LoginRequest\x1a\x19.helloworld.v1.LoginReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/login\x12i\n" +
	"\vGetUserInfo\x12!.helloworld.v1.GetUserInfoRequest\x1a\x1f.helloworld.v1.GetUserInfoReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/user/infoB%Z#kratos-example/api/helloworld/v1;v1b\x06proto3"

var (
	file_helloworld_v1_user_proto_rawDescOnce sync.Once
	file_helloworld_v1_user_proto_rawDescData []byte
)

func file_helloworld_v1_user_proto_rawDescGZIP() []byte {
	file_helloworld_v1_user_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_user_proto_rawDesc), len(file_helloworld_v1_user_proto_rawDesc)))
	})
	return file_helloworld_v1_user_proto_rawDescData
}

var file_helloworld_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_helloworld_v1_user_proto_goTypes = []any{
	(*LoginRequest)(nil),       // 0: helloworld.v1.LoginRequest
	(*LoginReply)(nil),         // 1: helloworld.v1.LoginReply
	(*GetUserInfoRequest)(nil), // 2: helloworld.v1.GetUserInfoRequest
	(*GetUserInfoReply)(nil),   // 3: helloworld.v1.GetUserInfoReply
}
var file_helloworld_v1_user_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.User.Login:input_type -> helloworld.v1.LoginRequest
	2, // 1: helloworld.v1.User.GetUserInfo:input_type -> helloworld.v1.GetUserInfoRequest
	1, // 2: helloworld.v1.User.Login:output_type -> helloworld.v1.LoginReply
	3, // 3: helloworld.v1.User.GetUserInfo:output_type -> helloworld.v1.GetUserInfoReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_v1_user_proto_init() }
func file_helloworld_v1_user_proto_init() {
	if File_helloworld_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_user_proto_rawDesc), len(file_helloworld_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_user_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_user_proto_depIdxs,
		MessageInfos:      file_helloworld_v1_user_proto_msgTypes,
	}.Build()
	File_helloworld_v1_user_proto = out.File
	file_helloworld_v1_user_proto_goTypes = nil
	file_helloworld_v1_user_proto_depIdxs = nil
}
