// Code generated by hertz generator.

package main

import (
	sahertz "github.com/click33/sa-token-go/integrations/hertz" // 只需这一个导入！
	"github.com/click33/sa-token-go/storage/memory"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	// 初始化（所有功能都在 sahertz 包中）
	storage := memory.NewStorage()
	config := sahertz.DefaultConfig()              // 使用 sahertz.DefaultConfig
	manager := sahertz.NewManager(storage, config) // 使用 sahertz.NewManager
	sahertz.SetManager(manager)                    // 使用 sahertz.SetManager

	h := server.Default()

	register(h)
	h.Spin()
}
